name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

      - name: obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"
      

  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest

    env:
      salida: ${{ needs.first_jobs.outputs.salida}}

    steps:
      - name: Hola Mundo
        run: echo "$salida"