name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      name: CodigoFacilito

    steps:
      - name: working dir
        run: echo $GITHUB_OUTPUT
      

  second_jobs:
    if: ${{github.ref == 'refs/heads/yaml'}}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo"